name: Assignment Workflow

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 24f3002267@ds.study.iitm.ac.in
        run: echo "This step contains my email address."
